@startuml
!include style.puml
skinparam ArrowFontStyle plain

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":AddressBookParser" as AddressBookParser LOGIC_COLOR
participant "cc:CreateClassCommand" as CreateClassCommand LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
end box

[-> LogicManager : execute("createClass d/Monday ti/H14")
activate LogicManager

' The AddressBookParser handles the creation of the specific command object.
' The CreateClassCommandParser is an implementation detail and is omitted for clarity.
LogicManager -> AddressBookParser : parseCommand("createClass ...")
activate AddressBookParser

create CreateClassCommand
AddressBookParser -> CreateClassCommand : new CreateClassCommand(day, time)
activate CreateClassCommand

CreateClassCommand --> AddressBookParser
deactivate CreateClassCommand

AddressBookParser --> LogicManager : cc
deactivate AddressBookParser

LogicManager -> CreateClassCommand : execute(model)
activate CreateClassCommand

' The command checks if the class already exists.
CreateClassCommand -> Model : hasTuitionClass(toAdd)
activate Model
Model --> CreateClassCommand : false
deactivate Model

' If not, the command adds the new class to the model.
CreateClassCommand -> Model : addTuitionClass(toAdd)
activate Model
Model --> CreateClassCommand
deactivate Model

CreateClassCommand --> LogicManager : result
deactivate CreateClassCommand
' The command object is destroyed after execution.
CreateClassCommand -[hidden]-> LogicManager
destroy CreateClassCommand

[<--LogicManager
deactivate LogicManager
@enduml
